// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrate, studio) must bypass the Neon pooler: PgBouncer transaction
    // pooling breaks Prisma Migrate's advisory locks. The app itself keeps using the
    // pooled DATABASE_URL through the driver adapter in src/lib/prisma.ts.
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
