const products = [
{id:'origines',name:'Origines',category:'tee',type:'T-shirt · Ivoire',color:'Ivoire',hex:'#e4decf',price:65000,image:'assets/product-origines.webp',tag:'01 / T-SHIRT',description:'Le rouge signature de Mahaleo sur un t-shirt ivoire. Le nom du groupe et son année de naissance, comme un souvenir que l’on transmet.'},
{id:'heritage',name:'Héritage',category:'tee',type:'T-shirt · Noir délavé',color:'Noir délavé',hex:'#353735',price:65000,image:'assets/product-heritage.webp',tag:'02 / T-SHIRT',description:'La signature rouge de Mahaleo sur un noir délavé. Une proposition inspirée des t-shirts de concert que l’on garde longtemps.'},
{id:'ensemble',name:'Ensemble',category:'sweat',type:'Sweat · Vert forêt',color:'Vert forêt',hex:'#264638',price:125000,image:'assets/product-ensemble.webp',tag:'03 / SWEAT',description:'Le nom du groupe, tout près du cœur. Une proposition de sweat à col rond et signature brodée.'}
];
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('fr-FR').format(n)+' Ar';
let filter='all',page=0,activeProduct=null,chosenSize=null,cart=[];
function perPage(){return innerWidth<=600?1:innerWidth<=900?2:3}
function filtered(){return products.filter(p=>filter==='all'||p.category===filter)}
function render(){const items=filtered(),count=perPage(),pages=Math.ceil(items.length/count);page=Math.max(0,Math.min(page,pages-1));$('#result-count').textContent=String(items.length).padStart(2,'0');$('#products').innerHTML=items.slice(page*count,(page+1)*count).map(p=>`<article class="product"><span class="product-catalog">${p.tag}</span><button class="product-image" data-product="${p.id}" aria-label="Voir ${p.name}, ${p.type}, ${money(p.price)}"><img src="${p.image}" alt="${p.type} Mahaleo, modèle ${p.name}"><span class="product-add" aria-hidden="true">+</span></button><div class="product-info"><div class="product-line"><button class="product-name" data-product="${p.id}">${p.name}</button><span class="price">${money(p.price)}</span></div><p class="product-type">${p.type}</p><div class="product-meta"><span class="swatch" style="--swatch:${p.hex}" role="img" aria-label="${p.color}"></span><span>S — M — L — XL</span></div></div></article>`).join('');$('#page-count').textContent=String(page+1).padStart(2,'0')+' / '+String(pages).padStart(2,'0');$('#prev').disabled=page===0;$('#next').disabled=page>=pages-1}
function openProduct(id){const p=products.find(p=>p.id===id);if(!p)throw Error('Produit inconnu');activeProduct=p;chosenSize=null;$('#detail-title').textContent=p.name;$('#detail-price').textContent=money(p.price);$('#detail-description').textContent=p.description;$('#detail-image').src=p.image;$('#detail-image').alt=p.type+' Mahaleo';$('#detail-color').innerHTML=`<span class="swatch" style="--swatch:${p.hex}"></span>${p.color}`;$('#sizes').innerHTML=['S','M','L','XL'].map(s=>`<button data-size="${s}" aria-pressed="false">${s}</button>`).join('');$('#size-status').textContent='';$('#product-dialog').showModal()}
function showToast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function addItem(id,size){const p=products.find(p=>p.id===id);if(!p||!['S','M','L','XL'].includes(size))throw Error('Produit ou taille invalide');const line=cart.find(c=>c.id===id&&c.size===size);if(line)line.quantity++;else cart.push({id,size,quantity:1});syncCount();showToast(p.name+' · '+size+' ajouté au panier');return {items:cart.reduce((n,c)=>n+c.quantity,0)}}
function syncCount(){$('#cart-count').textContent=cart.reduce((n,c)=>n+c.quantity,0)}
function renderCart(){const count=cart.reduce((n,c)=>n+c.quantity,0);$('#cart-title-count').textContent='('+count+')';$('#cart-items').innerHTML=cart.length?cart.map((c,i)=>{const p=products.find(p=>p.id===c.id);return `<div class="cart-row"><img src="${p.image}" alt="${p.type}"><div><h3>${p.name}</h3><p>${p.color} · Taille ${c.size}</p><div class="quantity"><button data-quantity="${i}" data-delta="-1" aria-label="Retirer une unité de ${p.name}">−</button><span>${c.quantity}</span><button data-quantity="${i}" data-delta="1" aria-label="Ajouter une unité de ${p.name}">+</button></div></div><div class="cart-price">${money(p.price*c.quantity)}<button class="remove" data-remove="${i}">Retirer</button></div></div>`}).join(''):'<div class="empty-cart">Votre panier attend sa première pièce.</div>';$('#cart-bottom').innerHTML=cart.length?`<div class="total"><span>Sous-total</span><strong>${money(cart.reduce((n,c)=>n+products.find(p=>p.id===c.id).price*c.quantity,0))}</strong></div><button class="primary" id="checkout">Continuer vers la commande <span>↗</span></button><p class="sample-note">Panier de démonstration · aucun paiement ne sera effectué.</p>`:'<button class="primary" data-close>Découvrir la collection <span>↗</span></button>'}
function info(title,body){$('#info-title').textContent=title;$('#info-body').innerHTML=body;$('#info-dialog').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close')){b.closest('dialog').close();return}if(b.dataset.product){openProduct(b.dataset.product);return}if(b.dataset.filter){filter=b.dataset.filter;page=0;document.querySelectorAll('[data-filter]').forEach(x=>{const yes=x===b;x.classList.toggle('active',yes);x.setAttribute('aria-pressed',yes)});render();return}if(b.dataset.size){chosenSize=b.dataset.size;document.querySelectorAll('[data-size]').forEach(x=>{const yes=x===b;x.classList.toggle('selected',yes);x.setAttribute('aria-pressed',yes)});$('#size-status').textContent='Taille '+chosenSize+' sélectionnée';return}if(b.hasAttribute('data-quantity')){const i=Number(b.dataset.quantity);cart[i].quantity+=Number(b.dataset.delta);cart=cart.filter(c=>c.quantity>0);syncCount();renderCart();return}if(b.hasAttribute('data-remove')){cart.splice(Number(b.dataset.remove),1);syncCount();renderCart();return}if(b.id==='checkout'){info('La suite de la commande', '<p>Vous avez parcouru la maquette jusqu’au panier. Lors de la création de la boutique, cette étape accueillera les coordonnées, la livraison et le paiement.</p><p>Aucune commande n’est transmise dans cette démonstration.</p>');}});
$('#prev').onclick=()=>{page--;render()};$('#next').onclick=()=>{page++;render()};
$('#add-to-cart').onclick=()=>{if(!chosenSize){$('#size-status').textContent='Sélectionnez une taille pour continuer.';$('#sizes button').focus();return}addItem(activeProduct.id,chosenSize);$('#product-dialog').close()};
$('#cart-open').onclick=()=>{renderCart();$('#cart-dialog').showModal()};
$('#history-open').onclick=()=>info('L’histoire commence en 1972.',`<img class="archive" src="assets/mahaleo-1972.jpg" alt="Les sept musiciens de Mahaleo en 1972"><small>Mahaleo, 1972 · © Lucien Rajaonina · Source : Mahaleo.com / Laterit</small><p>Né à Antsirabe pendant le mouvement étudiant de mai 1972, Mahaleo fait entendre une voix profondément malgache. Guitares, chants, amitié et engagement : la musique raconte les aspirations et la vie quotidienne d’un peuple.</p><p>Cette proposition de collection reprend le nom du groupe et son année de naissance, avec la signature rouge fournie pour cette proposition et une mise en page inspirée de la presse musicale et des pochettes de disques.</p><p><a href="https://www.mahaleo.com/groupe.htm" target="_blank" rel="noopener">L’histoire du groupe sur Mahaleo.com ↗</a></p><small>Direction artistique proposée. Le logo a été fourni pour cette maquette. Les vêtements et leurs marquages restent des propositions de collection.</small>`);
$('#info-open').onclick=()=>info('Livraison & retours','<p>Les destinations, transporteurs, frais de livraison et conditions de retour seront définis avec l’équipe Mahaleo avant l’ouverture de la boutique.</p><p>Les tarifs affichés sont indicatifs. Aucun achat réel n’est possible dans cette maquette.</p>');
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
let oldSize=perPage();window.addEventListener('resize',()=>{if(oldSize!==perPage()){oldSize=perPage();page=0;render()}});render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const t of [{name:'list_mahaleo_products',title:'Voir les vêtements Mahaleo',description:'Lire les produits et les prix indicatifs de cette maquette.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>products.map(({id,name,price,category})=>({id,name,price,currency:'MGA',category,sizes:['S','M','L','XL']}))},{name:'open_mahaleo_product',title:'Ouvrir une fiche produit',description:'Afficher la fiche produit sans ajouter au panier.',inputSchema:{type:'object',properties:{id:{type:'string',enum:products.map(p=>p.id)}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({id})=>{openProduct(id);return{opened:id}}}]){try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}}}
